const colors = require("tailwindcss/colors");
module.exports = {
  purge: ["./pages/**/*.js", "./components/**/*.js"],
  darkMode: !1,
  theme: {
    fontSize: {
      "3xs": ".2rem",
      "2xs": ".3rem",
      xxs: ".6rem",
      xs: ".75rem",
      sm: ".875rem",
      tiny: ".875rem",
      base: "1rem",
      lg: "1.125rem",
      xl: "1.25rem",
      "2xl": "1.5rem",
      "3xl": "1.875rem",
      "4xl": "2.25rem",
      "5xl": "3rem",
      "6xl": "4rem",
      "7xl": "5rem",
    },
    screens: {
      xxs: "200px",
      xs: "440px",
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1536px",
    },
    extend: {
      fontFamily: { poppins: ["Poppins"] },
      grayscale: {
        10: "10%",
        20: "20%",
        30: "30%",
        40: "40%",
        50: "50%",
        60: "60%",
        70: "70%",
        80: "80%",
        90: "90%",
      },
    },
    colors: {
      green: {DEFAULT:"#2FDD92"},
      red: {DEFAULT:"#CD1818"},
      yellow: { DEFAULT: "#ffed00" },
      blue: { DEFAULT: "#12326e" },
      white: { DEFAULT: "#ffffff" },
      gray: { DEFAULT: "#f9f9f9" },
      black: { DEFAULT: "#0000" },
      skyblue: { DEFAULT: "#88E0EF" },
      otherblue: { DEFAULT: "#253C78" },
      twitter: { DEFAULT: "#1DA1F2" },
      facebook: { DEFAULT: "#4267B2" },
      whatsapp1: {DEFAULT: "#25D366"},
      whatsapp2: {DEFAULT: "#075E54"},
      instagramYellow: { DEFAULT: "#fccc63" },
      instagramOrange: { DEFAULT: "#fbad50" },
      instagramMaroon: { DEFAULT: "#cd486b" },
    },
  },
  variants: {
    extend: {
      backGround: [
        "responsive",
        "dark",
        "group-hover",
        "focus-within",
        "hover",
        "focus",
        "active",
      ],
      filter: [
        "responsive",
        "dark",
        "group-hover",
        "focus-within",
        "hover",
        "focus",
        "active",
      ],
      opacity: [
        "responsive",
        "dark",
        "group-hover",
        "focus-within",
        "hover",
        "focus",
        "active",
      ],
      display: [
        "responsive",
        "dark",
        "group-hover",
        "focus-within",
        "hover",
        "focus",
        "active",
      ],
      textColor: [
        "responsive",
        "dark",
        "group-hover",
        "focus-within",
        "hover",
        "focus",
        "active",
      ],
      borderRadius: ["hover", "focus"],
    },
  },
  plugins: [],
};
